### ISSUE TITLE
discovery.py doesn't discover Roku 4

### ISSUE THREAD

**Issue by alphor** [jcarbaugh/python-roku#19]
But it _does_ provoke a response from it:

tcpdump output during a Roku.discover() call:
``` bash
tcpdump -ne -i any port 1900
21:32:43.638146 Out <ma:ca:dd:re:ss> ethertype IPv4 (0x0800), length 138: 192.168.1.2.34202 > 239.255.255.250.ssdp: UDP, length 94
21:32:46.063044  In <ma:ca:dd:re:ss> ethertype IPv4 (0x0800), length 259: 192.168.1.8.ssdp > 192.168.5.2.34202: UDP, length 215
```

192.168.1.8 is indeed a Roku, so it's not the cast, it's the response not being picked up by the socket. 

For a workaround I just query arp tables for the IP using something like:

```bash
ip neigh | awk '/ro:ku:ma:ca:dr/ { print $1 }' | tr -d '()'
```
and pass it to the application. This issue seems like a recurring issue with Python and multicast requests, so this can (and probably should) be closed, unless someone knows what's going on. I just figured this might be a good place to put it for those who ran into the same problem.

**Comment by gsparx** [comment]
I'm seeing similar behavior I believe.  I've tried several different python implementations, and a golang implementation (my server is written in golang) and my Roku4 does not show up in the device list at all.  It's driving me nuts.  The Roku remote app discovers my Roku just fine (and I'm assuming it would also be using SSDP for this?) and I am at a complete loss as to why I can't use fairly vanilla SSDP discovery code to discover the Roku.

```
20:26:08.592797 <routerma:ca:dd:re:ss> > <unknownma:ca:dd:re:ss>, ethertype IPv4 (0x0800), length 136: 192.168.1.9.62042 > 239.255.255.250.1900: UDP, length 94
20:26:09.505483 <rokuma:ca:dd:re:ss> > <routerma:ca:dd:re:ss>1, ethertype IPv4 (0x0800), length 257: 192.168.1.10.1900 > 192.168.1.9.62042: UDP, length 215
```

My TCPdump looks a bit different from yours though (I'm on osx)

192.168.1.10 is definitely my roku device's IP.  Any thoughts?

**Comment by iantrich** [comment]
Closing as this looks to be a configuration issue. Let me know if issue persists. Thanks!

**Comment by daranday** [comment]
Running into this issue as well on MacOS Mojave.
Roku.discover() works the first time but not subsequent times until kernel is restarted.
