### ISSUE TITLE
Implement Search for the External Control API

### ISSUE THREAD

**Issue by keatontaylor** [jcarbaugh/python-roku#22]
This is a placeholder for a pull request I intend to work on that will allow search queries via the python library following the external control api. The end goal is to provide home assistant the means for launching searches so that it can be implemented with the new video skills api provided by alexa.

Essentially this:

Alexa play Game of Thrones Season 1 Episode 5.

Video Skills Api will parse show name, season # and episode # then pass along to haaska for processing which will pass the parameters along to home assistant which is running locally to call and ultimately call the python-roku library to execute a search. 

For shows that can be found exactly, auto launching can occur. (Works for netflix, but not for HBO GO)

**Comment by iantrich** [comment]
Search has been implemented in https://github.com/jcarbaugh/python-roku/pull/36
