### ISSUE TITLE
Power control?

### ISSUE THREAD

**Issue by timdenike** [jcarbaugh/python-roku#24]
Any plans to push power control to python-roku?  I see you were experimenting with this in another thread.  Happy to assist!   I'm able to power on the unit with WOL, not sure how to shut it off, yet.

**Comment by ifuchs** [comment]
I was wondering the same thing. Power control would be a nice addition.

**Comment by robertw** [comment]
+2 vote for power control .......

**Comment by lewiswharf** [comment]
> I'm able to power on the unit with WOL, not sure how to shut it off, yet.

Run same command again.

**Comment by jcarbaugh** [comment]
@timdenike if you have working WOL code, it would be a huge help! I've been making multiple attempts at waking my TCL Roku TV and haven't had any luck.

**Comment by Valdorama** [comment]
@jcarbaugh - have you seen this discussion?:

https://community.home-assistant.io/t/roku-tv-support/15406

**Comment by CSCG** [comment]
@jcarbaugh I just got it to work on my TCL 55" Roku. Just this week, an option popped up in the Roku Remote Android App to leave my Roku on 'instant-on' mode. With this instant on mode enabled, it seems to leave the networking connected. 

When I fire this code, it wakes it almost instantly! Maybe this next week I can merge my changes that provide method access to power. This worked on my Insignia too when I enabled instant on. 

Example (I'm at work, might be fuzzy):

`Roku._post('/keypress/Power') # essentially sending a CURL request to 'http://<tv ip address>:8060/keypress/Power'`

**Comment by ifuchs** [comment]
It would be great to see power on/off/status commands added. I tried the URL <http://<tv ip address>:8060/keypress/Power> but it did not seem to work.

**Comment by cwhits** [comment]
@CSCG status should be available at `http://roku:8060/query/device-info`
`<power-mode>DisplayOff</power-mode>`

**Comment by mdeneen** [comment]
https://github.com/jcarbaugh/python-roku/pull/29
