### ISSUE TITLE
New release pushed to pypi?

### ISSUE THREAD

**Issue by bah2830** [jcarbaugh/python-roku#28]
It has been a while since pypi was updated. I have looked into updating pypi but the project is still versioned at 2.0.

I would like to get a 2.1 pushed and pypi updated

**Comment by soberstadt** [comment]
Hey @jcarbaugh, is there anything preventing a version bump at this point?

**Comment by TheDavidFactor** [comment]
I just had an issue with the pypi version that I found is fixed in the repo. So I also vote to update pypi

**Comment by soberstadt** [comment]
@iantrich @bah2830 I was going to submit a PR to HA to move to this repo, but we need a version bump. Does Ian have publish access as he is a contributor now?

**Comment by iantrich** [comment]
I do not have publish access yet. I've asked @jcarbaugh to add me and I hope to do some testing this week and put out a release this weekend.

**Comment by manutenfruits** [comment]
Hi @jcarbaugh @iantrich any updates? It'd be great to get the new version pushed, thanks!

**Comment by iantrich** [comment]
@jcarbaugh granted me access today after getting back from a trip 🎉 I'll try to push out the release tonight

**Comment by iantrich** [comment]
New release has been published: https://pypi.org/project/roku/

**Comment by jcarbaugh** [comment]
Thanks so much for doing this @iantrich !!!
