### ISSUE TITLE
Expose 'Model Type' device info property (especially useful for Roku TVs)

### ISSUE THREAD

**Issue by Valdorama** [jcarbaugh/python-roku#31]
I think it would be useful to provide the Model Type property of a Roku device (in addition to model name, model number etc.). This currently has value 'STB' for standard set top Rokus and 'TV' for Roku TVs, according to this:

[https://sdkdocs.roku.com/display/sdkdoc/ifDeviceInfo#ifDeviceInfo-GetModelType()asString](url)

This would allow consumers of this project (such as Home Assistant) to configure behaviour based on whether the device is a TV or not. Specifically, I'm thinking of something like this: "when polling the device and there's no response, if it's a STB consider that a warning, but if it's a TV, just assume it's off and set its status accordingly".

**Comment by iantrich** [comment]
https://github.com/jcarbaugh/python-roku/pull/37 will have a `roku_type`; Box vs Stick vs TV
