### ISSUE TITLE
r.apps is not a valid method

### ISSUE THREAD

**Issue by controversial** [jcarbaugh/python-roku#8]
The examples mention a r.apps method, which doesn't seem to work.

**Comment by jcarbaugh** [comment]
*apps* is actually a property, so it should be invoked as `r.apps` instead of `r.apps()`. Do you have some example code that would show the issue you've come across?

**Comment by The-Penultimate-Defenestrator** [comment]
I can't even make 
```
import roku

r = roku.Roku('192.168.1.110')
apps = r.apps
```
work. Is it an incompatibility with certain roku boxes?

**Comment by jcarbaugh** [comment]
Huh. Maybe. Does it throw an error or does apps just return an empty list?

**Comment by The-Penultimate-Defenestrator** [comment]
Throws an error from line 84 in

    def __getattr__(self, name):

        if name not in COMMANDS and name not in SENSORS:
            raise AttributeError('%s is not a valid method' % name)

**Comment by jcarbaugh** [comment]
And just for reference, are you using Python 2 or 3?

**Comment by The-Penultimate-Defenestrator** [comment]
Python 2. Other things that might matter but don't think so- running through pythonista on iOS. I replaced the import of `lxml` with `xml`, because I read the etree functions are basically the same. If this is the issue, I'll feel pretty stupid.

**Comment by The-Penultimate-Defenestrator** [comment]
I did get this to work on the same device with someone else's roku, still replacing `lxml` with `xml`. I assume it's an incompatibility with my Roku.

**Comment by adamsong** [comment]
Is the code not supposed to be
`from roku import Roku
r = Roku(ip)
r.apps`

**Comment by iantrich** [comment]
Fixed in https://github.com/jcarbaugh/python-roku/pull/36
